### ISSUE TITLE
Falta de identificação de comandos iniciando com "-".

### ISSUE THREAD

**Issue by MatheusFilipe95** [mateusvroriz/botuber#3]
Uma das formas mais comuns dos chatbots do discord é a utilização do carácter "-" no início dos comandos, notei que o bot só identifica "!", seria interessante aceitar as duas formas para que todos os usuários possam utilizar da forma que está acostumado.

**Comment by mateusvroriz** [comment]
Obrigado pelo feedback, esse erro já foi relatado antes por outros usuários do bot.
